export const GET_DATA_PRODUCTS = "GET_DATA_PRODUCTS";

export const START_GET_DATA_PRODUCTS = "START_GET_DATA_PRODUCTS";

export const STOP_GET_DATA_PRODUCTS = "STOP_GET_DATA_PRODUCTS";

export const GET_DATA_PRODUCTS_SUCCESS = "GET_DATA_PRODUCTS_SUCCESS";

export const GET_DATA_PRODUCTS_FAILED = "GET_DATA_PRODUCTS_FAILED";
