export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const START_SIGNUP = "START_SIGNUP";
export const SIGNUP_CANCELLED = "SIGNUP_CANCELLED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILLED";
